FROM nginx:alpine

# Copiamos la configuración personalizada de Nginx
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos los archivos estáticos al directorio de Nginx
COPY . /usr/share/nginx/html

# Exponemos el puerto 80
EXPOSE 80

# Nginx corre en primer plano por defecto
